### ISSUE TITLE
On small screens the lower section of the wallet is hidden behind the taskbar

### ISSUE THREAD

**Issue by kenodressel** [superhero-com/superhero-wallet#1243]
![image](https://user-images.githubusercontent.com/765921/126983267-bc786777-12e9-4ed4-b0a9-242213177929.png)

I this is the latest firefox on windows 10 with the following screen settings:
![image](https://user-images.githubusercontent.com/765921/126983520-17f82762-29c9-47b5-a8bc-81f70b6f4d3d.png)

**Comment by CedrikNikita** [comment]
@onvisions

**Comment by Liubov-crypto** [comment]
> @Liubov-crypto could you check if the wallet for this viewport scaling and check if this is fixed after a browser restart?

Checked on Windows 10, this issue is reproducible in Firefox when the browser is not fully deployed. Then the bottom menu of the wallet is either cropped or hidden altogether:

![зображення_viber_2021-10-14_13-49-54-175](https://user-images.githubusercontent.com/69896204/137312092-7a84ab46-9dd3-4565-a1ad-917ac3cf7525.jpg)

In the Chrome browser wallet scaling works fine.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems, because our menu is no longer at the bottom.
