### ISSUE TITLE
Add ETH account detail home

### ISSUE THREAD

**Issue by paolomolo** [superhero-com/superhero-wallet#2401]
This task covers displaying the Account Details page after clicking on the ETH account card on the dashboard.
The transaction list will be covered within separate task.

**Comment by Liubov-crypto** [comment]
LGTM.

One minor thing, I think it's worth to change text on Send modal from tokens to ETH: 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/7ba9e2e6-19b6-469f-a40b-76814aebb4ef)

Also, Idk if it's in scope, but will we add https://etherscan.io/ redirection instead of 404 page? 

https://github.com/superhero-com/superhero-wallet/assets/69896204/09c3c532-392c-4da4-95a5-ceebdfb6ce9a

**Comment by peronczyk** [comment]
I have rebased this branch with our main branch changes. So I think this needs another round of testing.

**Comment by dvdbak** [comment]
LGTM
