### ISSUE TITLE
Seed phrase screen confirmation is shifted

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2878]
**Describe the bug**
Seed phrase screen confirmation is shifted 

**To Reproduce**
1. Go to Verify seed phrase
2. Try to verify
3. See error

**Expected behavior**
Screens should match

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS:  iOS
 - Version 2.2.0 (1)

**Additional context**
Reproducible on release branch

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/f35762b6-8d85-456d-90e6-b024ea05896f)

**Comment by peronczyk** [comment]
I have replaced JS notification box position calculations with regular CSS approach: `position: relative;` on parent + `position: absolute; inset: 0;` on notification box.

Needed to make some HTML structure changes to this page in order to achieve this. Please test whole seed phrase verification process @liubov.

Also I moved common styles of the grey card and this page:

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/564dbdd1-37e8-4519-bfbe-11dc6772e2a9)

into separate component.
