### ISSUE TITLE
Create an Address Book for Contacts

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3036]
Address Book to be stored locally on Device. 
Import/Export functionality shall also be present.

**Comment by onvisions** [comment]
**Address Book** @smaroudasunicorn 

**1. Address book main screen (addresses list) mockups:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/ec100305-fe2d-4775-92bc-cfa03ea03904)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/207afc12-dbc0-4af1-a3c4-b1f00506b3ab)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/4b441752-6407-4486-b8fd-82300a00837a)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/ea3b0132-31b0-41ba-8d0e-9e5c2aee5830)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/8a7ee708-133a-412d-a9fa-24852f501fcc)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/c175d142-c1b4-4145-823c-45c9f4b62443)






**2. Address book single address record mockups:**


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/331393c6-7c10-4960-a4b1-e2ea3cf722ee)







**3. Address book Add address screen mockups:**


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/683548b8-1310-4e76-9707-b5b9ab14058c)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b627f26f-ae34-4892-983b-aae373a81ea7)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/007f985d-60b9-4c93-aca5-803feaa25c9d)




4. Address book modal (Send funds flow):
_work in progress..._

**Figma reference:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=31935-180432&t=gZlJbeKQFrjFsfqj-0

**Comment by smaroudasunicorn** [comment]
We want to be able to share my address to another address book

**Comment by smaroudasunicorn** [comment]
You need to be able to filter by name too

**Comment by onvisions** [comment]
**Address Book Design ** _(updated after feedback 31.05)_ @smaroudasunicorn @martinkaintas 

**1. Address book main screen (addresses list) mockups:**

Access Address book from the More screen. The "Address book" tab shows the number of address records:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/5401f807-fd4c-4827-96e5-f7a4f341277d)

Addresses list, filters, show all, show bookmarked (favourites), filter by blockchain:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/3925c0aa-e092-468c-8a53-f96a752cf059)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/f8b15f1b-32ee-44e4-9bdc-039a851ad4ec)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/da673fd9-4c9d-4578-a4bc-f175a6087414)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/9ae31f42-9a74-4c27-b901-4af70007a8e4)

No records messages:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/33857823-395d-420a-81b0-320136fe5755)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/bd954aa3-14e9-48a1-a44f-b736385c78bf)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/d462d615-a0f5-4e5d-b32b-67b4abde4908)

Scrolled Address records list (Search by name or address is shown); Multiple filters future proof support (with horizontal scroll of the blockchain filters):

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/1cbed205-69d6-43d2-a06e-1d489849f427)



**2 Address book - single address record (Edit):**


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/f5a42ed2-0359-4a5e-affe-c90e97723e1b)


**3. Address book - Add address record screen:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/1b85edd6-922e-4da6-a60d-981819e12a83)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/5bb53986-775f-4f9e-8b90-51b4e4e0f783)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/6dff6831-4aaa-4da7-9593-2b3e4b432ac1)

Errors:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/08abc970-4411-4135-b78e-7398b8d2354c)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/a559ffef-30b0-4aaf-b2f1-961f86d81531)


**4. Select address from Address Book modal (Send funds flow):**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/c9774781-b736-44d7-89fa-3f4ef59bdefe)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/39b06e11-d343-4a37-a0ad-53434b48fb0a)

Select account address from address book modal:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b9d866d3-28b5-44f7-91e4-8198ca7c0f7f)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/4db4f8ce-2f95-470b-a892-5b03eb4f8a65)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/c8b121f3-fae9-4de9-a4ee-3e5037e0ba92)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b6ca5153-cc2b-4a76-aa07-8ff571872b68)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/08b302b0-48d8-48a6-b03e-618b152e720f)


5. Add show QR feature to Account Details to easily share user's account address. Thus another user can scan it in order to add address to the Address Book. The focus is only on sharing the QR code VS existing feature of Receive modal. Design:
 _work in progress..._

6. Prototype recording: 
 _work in progress..._


**Figma reference:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=31935-180432&t=gZlJbeKQFrjFsfqj-0

**Comment by onvisions** [comment]
@smaroudasunicorn @martinkaintas 

Add "Share your public address" feature to Account Details to easily share user's currently active account address. Thus another user can scan it in order to add address to the Address Book.
The focus is only on sharing the QR code VS existing feature of Receive modal. **Design:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/453db48f-7fe4-465f-9bde-c8598f946524)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/094058d9-d5d0-4623-809f-66217ea865d1)

"Share your public address" prototype:

https://github.com/superhero-com/superhero-wallet/assets/12225410/7a993f23-9cf5-4a3a-88a4-fec254023103

**Comment by onvisions** [comment]
@martinkaintas @smaroudasunicorn 
**Address book default ordering within the address records list.**

Alphabetical, with numbers first:

1 Trading Uniswap
2John Doe
Alf
salary account
.....................

Thus the user will have some control over the ordering of address book records in the list through custom naming.

Beyound the MVP we can think of functionality to reorder addresses/accounts in the list by dragging the list items up and down. This will be useful not only for address book but also for the account management as it may change the default order of the account cards in the switcher. IMO we should include it in some user stories for extended "Account management" and "Address book records management". These may also include batch actions such as remove/delete multiple accounts/address records.

**Comment by onvisions** [comment]
> a minor comment. Change add address button to add....

![1 1 Address book - all](https://github.com/superhero-com/superhero-wallet/assets/12225410/e42ef199-cb1d-46e9-9621-248c2e30ccc0)

**Comment by martinkaintas** [comment]
Created a separate task for [Address Book: Send to address book record #3104](https://github.com/superhero-com/superhero-wallet/issues/3104)

**Comment by Liubov-crypto** [comment]
Found minor design discrepancies on this screen, please check it: 

- link to the address
- name symbols counter
- additional word "blockchain' in Address field


![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/48fa82db-a5d0-4e97-bd73-6b3cbaba86b3)


![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/7ff99403-d53b-4add-97bd-60cef2c0759a)

the rest is LGTM

**Comment by martinkaintas** [comment]
> * additional word "blockchain' in Address field

This is according to the design in Figma, @onvisions please lmk which one should be used

**Comment by onvisions** [comment]
- In the context of an Address book and adding an address "Enter public blockchain address" bring more clarity to the user than just "Enter public address".

- Character counter is part of the design and should be implemented. 50 characters are too many for name of an Address book record. According to design it's 33 but now I'm thinking if we even need more than 20. 
@martinkaintas we need to implement some shortening for the names to fit different UI spots so I suggest to use the component with the horizontal animation that we use for .chain names.
@Liubov-crypto Can we test with a longer name to see how it's displayed at the moment with the current implementation? 
- The Bookmark button is not implemented as designed. Visual discrepancies and button has a fixed width. Only label changes so that it doesn't "jump" when its state is updated.

**Comment by Liubov-crypto** [comment]
Now it looks better: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/509b6a9f-d85c-4a89-b5d4-64184f1fd89c

@onvisions what do you think about Bookmark?

**Comment by onvisions** [comment]
For the character counter we have design reference:

![image](https://github.com/superhero-com/superhero-wallet/assets/12225410/e8ab7c14-3a9b-4137-957c-b505e8670416)

However I noticed it has not been implemented in this way across the UI so if this is the case (@martinkaintas please confirm) I suggest to create a separate sotry for UX/UI improvement of the feature.

**Comment by Liubov-crypto** [comment]
LGTM
