### ISSUE TITLE
Enrich Token Sent Transactions

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3084]
For example

![Image](https://github.com/superhero-com/superhero-wallet/assets/103504859/d4ced01a-cecf-4c47-b44c-55368278ea83)

sent tx for AEX-9 token with transaction fee in AE displayed as well but instead the AEX-9 token should be on top and AE below

This shall apply for ERC-20 tokens too.

**Comment by Liubov-crypto** [comment]
In terms of Tx and details LGTM. 
But I see that The Latest Tx widget is displaying only 2 Tx instead of 3 compared to dev. Probably affected these changes. 
I would like to test it again after review. 

pr:

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/dd0e2d7f-39fd-4778-98c3-ebe238e606a1)

develop: 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/655fd6d8-bea7-4abb-889e-cbf5f393b403)

**Comment by onvisions** [comment]
Except for the AE transactions the fee can be included in the amount as it requires no additional line or space to be displayed. So if sending 10 AE with 0.0001692 fee we may show - 10.0001692 AE. What do you think? @smaroudasunicorn

**Comment by Liubov-crypto** [comment]
I assume that we decided to stay Latest Tx widget as it is. The rest is LGTM
