### ISSUE TITLE
Ability to import/export Private Key (backup)

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3188]
STORY:

User has to be able to export wallet private keys encrypted. User has to be able to restore wallet accounts with the encrypted key(s) and the password. 

DESIGN:

_1. Import with Seed phrase VS Import with Private key(s) and password:_

**Import wallet accounts with Private Key:**

![Image](https://github.com/user-attachments/assets/6f0fe8b0-2a3c-4f5b-9e68-00d0041ce119)

![Image](https://github.com/user-attachments/assets/656e2e97-dc8c-470a-b919-86c0ad16a1ee)

![Image](https://github.com/user-attachments/assets/f332d630-c85b-4df6-aff5-83784334aae0)

![Image](https://github.com/user-attachments/assets/0e9e5dc5-a554-4584-9559-1d8098b67132)

![Image](https://github.com/user-attachments/assets/0e12bf3f-bd82-43f4-b1ad-3b1bccdfd761)

![Image](https://github.com/user-attachments/assets/c14a5575-e9e5-406b-bec7-900f62d1bd7a)

![Image](https://github.com/user-attachments/assets/04f18057-daa1-4310-968e-f47c32a987bc)

**Import wallet accounts with Seed phrase:**

![Image](https://github.com/user-attachments/assets/6f0fe8b0-2a3c-4f5b-9e68-00d0041ce119)

![Image](https://github.com/user-attachments/assets/656e2e97-dc8c-470a-b919-86c0ad16a1ee)

![Image](https://github.com/user-attachments/assets/f332d630-c85b-4df6-aff5-83784334aae0)

![Image](https://github.com/user-attachments/assets/123a84ca-bdce-4667-a827-ad8c1a0bd139)

![Image](https://github.com/user-attachments/assets/c30bb362-d844-4bc6-8265-02eb28d341d4)

![Image](https://github.com/user-attachments/assets/04f18057-daa1-4310-968e-f47c32a987bc)

.....................................................................................
_2. Export private key(s):_ 

!! See Figma comments (follow the reference link below)

![Image](https://github.com/user-attachments/assets/922b154a-e991-4106-a269-7d5565b97d25)

![Image](https://github.com/user-attachments/assets/a7b37412-1521-4579-912c-6c0378898e67)

![Image](https://github.com/user-attachments/assets/01321a42-5527-400f-8eed-59ee5040e16d)

![Image](https://github.com/user-attachments/assets/3620efb0-df52-46e8-9f7a-26ecf3f82343)

![Image](https://github.com/user-attachments/assets/b51b5675-e5e9-4442-9a79-53969ad2029f)

![Image](https://github.com/user-attachments/assets/38473453-0117-4b25-a72e-a3a8dd050cf4)

![Image](https://github.com/user-attachments/assets/eefed66a-53cc-4302-b76a-02c18002d865)

.....................................................................................
FIGMA REFERENCE: https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=33646-210502&t=yNhx5Cr7FQ1SiG9h-0

**Comment by nikita-fuchs** [comment]
Hey, so awesome to see this moving !

**I.** 
![image](https://github.com/user-attachments/assets/2af71c45-e432-4f65-a58a-6150edd878a7)

1. Improve phrasing: " ..export your private key in plain text format or as a .json or .csv file" (is that correct? or will plain text also be a file?)
2. What is meant by "current wallet password" - will there be a protection accessing SH wallet, like in metamask? If so, maybe adapt the wording to "current SUperhero Wallewt password" so (less technical) people don't mix it with the private key of one account.

**II.** Right now, all accounts except the main one are derived from the main seed phrase.

**Comment by CedrikNikita** [comment]
> will there be a protection accessing SH wallet, like in metamask?

Yes.

> How is that handled in the future, when derived and imported (via PK import) accounts mix ?

The idea is to let user initiate wallet with one private key. If the user will want to add new accounts, he will be offered to add a seed phrase or import another private key.

> Are all PKs for the derived accounts stored somewhere, so that technically all accounts (derived and PK-imported) can be treated equally in terms of exporting, e.g. I am responsible / have the possibility to export/import all PKs of all accounts?

Yes, they will be stored "somewhere", and can be exported equally. We should think about having option "export all the accounts".

**Comment by nikita-fuchs** [comment]
Alright, awesome.  Then basically the role of importing an account with a mnemonic will be limited to deriving a keypair at index `0` only, right ? As a _bonus feature_, you could ask users which index they want to derive the account from, for the case that some people rely on this feature.

**Comment by CedrikNikita** [comment]
> Alright, awesome. Then basically the role of importing an account with a mnemonic will be limited to deriving a keypair at index `0` only, right ? 

No. It will remain the same. You just would be able to import a private key in addition to existing functionality.
> As a _bonus feature_, you could ask users which index they want to derive the account from, for the case that some people rely on this feature.

We have a separate ticket for this feature.

**Comment by onvisions** [comment]
@nikita-fuchs @CedrikNikita @smaroudasunicorn @martinkaintas 

1. Replying to @nikita-fuchs' questions:
- "plain text" means .txt file;
- yes, we're implementing password protection (as in Metamask for example).

2. **However** I also have couple of unclear questions regarding the private keys. Currently I have designed the feature as discussed within our team meetings. As follows...
 
- "exporting the private key" means exporting a .txt, .json. or .csv file containing encrypted string with all wallet accounts derived from the same seed phrase. 
- The user is able to restore the wallet alternatively by entering seed phrase or using the exported private key.  
- The user is not able to import accounts derived from different mnemonics neither they are able to export/import a specific single account.
- The import private key option is available only on the initial screens. If we'd like to allow user to import any account with its private key we have to add this option to the "Add account" modal as well. However this will require the ability to export specific selected accounts only and also the ability to import in one wallet accounts derived from different seed phrases.

And that's what's not clear to me. I noticed other wallets allow the users to export private key for each account they have in the wallet _separately_ so that later they can import only the given account to another installation of the extension. Our approach is different as we discussed to export one encrypted key restoring the whole wallet with all accounts derived from the same seed (including different blockchains accounts - Ethereum, Bitcoin, Solana etc.) 
Should we also support exporting separately private key for a single account? 
Should we have option to select (with checkboxes) which accounts to export? 
May be we can have also option to export accounts by blockchain such as "export all Bitcoin accounts for example".

**Comment by onvisions** [comment]
UPDATED DESIGN:

1. Export Private Key (Show & Copy PK):



2. Import private key from Add account modal:



3. Import private key from Welcome screen:



4. Import single multisig vault with PK:Figma Reference: 



https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=33899-223886&t=XmtLNGNeNUNi3hAy-0

**Comment by nikita-fuchs** [comment]
good job @onvisions  !
